### ISSUE TITLE
skeleton fails to compile with clang ToT 

### ISSUE THREAD

**Issue by LegalizeAdulthood** [bloomberg/clangmetatool#36]
**Describe the bug**
Attempting to build the skeleton results in a link error.

**To Reproduce**
1. git clone https://github.com/llvm-mirror/llvm.git @ a10a70238ace1093cad3adeb94814b422bd1b5c1
2. cd llvm/tools
3. git clone https://github.com/llvm-mirror/clang.git @ 6ed0749151866894a67a3e7eefdc1f3a547daa0e
3. cd clang/tools
4. git clone https://github.com/llvm-mirror/clang-tools-extra.git @ d0fd727a5aa3776e4d49061de933772cf7d26c4c
5. Build clang and install to local dir
6. git clone https://github.com/bloomberg/clangmetatool.git @ 398a4788e8e6ede5fe1f6800310fe4510a46e7c0
7. Build clangmetatool and install to local dir (same as clang)
8. Copy skeleton to new git repository and change tool name in CMakeLists.txt
9. Configure with CMake; no problems
10. Build and get link error

```
$ make -j40
Scanning dependencies of target mock-api-tool
[ 50%] Building CXX object CMakeFiles/mock-api-tool.dir/src/main.cpp.o
[100%] Linking CXX executable mock-api-tool
CMakeFiles/mock-api-tool.dir/src/main.cpp.o:(.rodata._ZTIN13clangmetatool15MetaToolFactoryINS_8MetaToolI6MyToolEEEE[_ZTIN13clangmetatool15MetaToolFactoryINS_8MetaToolI6MyToolEEEE]+0x10): undefined reference to `typeinfo for clang::tooling::FrontendActionFactory'
CMakeFiles/mock-api-tool.dir/src/main.cpp.o:(.rodata._ZTIN13clangmetatool8MetaToolI6MyToolEE[_ZTIN13clangmetatool8MetaToolI6MyToolEE]+0x10): undefined reference to `typeinfo for clang::ASTFrontendAction'
collect2: error: ld returned 1 exit status
CMakeFiles/mock-api-tool.dir/build.make:122: recipe for target 'mock-api-tool' failed
make[2]: *** [mock-api-tool] Error 1
CMakeFiles/Makefile2:131: recipe for target 'CMakeFiles/mock-api-tool.dir/all' failed
make[1]: *** [CMakeFiles/mock-api-tool.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Expected behavior**
Skeleton should compile and link without errors before any original modifications are made.

**Environment (please complete the following information):**
 - Operating System and Version: 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- g++ --version reports g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

**Comment by ruoso** [comment]
It seems you're mixing rtti-enabled and rtti-disabled code. Can you take a look at the steps taken from the `.travis.clang8.Dockerfile` and see if it works for you?

**Comment by LegalizeAdulthood** [comment]
clang-7 and clang-8 packages aren't available for me through apt...

**Comment by ruoso** [comment]
The travis file is using from a prebuilt release out of the main repo...

**Comment by LegalizeAdulthood** [comment]
My build steps for the skeleton are the same as yours except my Clang_DIR and clangmetatool_DIR values are local directories not system directories.

**Comment by LegalizeAdulthood** [comment]
Unfortunately this is a shared machine, I can't just globally change the C++ compiler like that.

**Comment by ruoso** [comment]
Ok, I'll get someone to try and reproduce your problem on our end... I suspect there's something wrong going on in the llvm and clang configurations that is leaving you with an rtti-disabled build.

**Comment by ruoso** [comment]
Can you confirm the version of ubuntu that you're using? (you listed the kernel version and a package version, and it seems to be 16.04, but I just want to be sure).

**Comment by LegalizeAdulthood** [comment]
```

**Comment by LegalizeAdulthood** [comment]
I looked through the imported target definitions created in the config files and while they define link dependencies and clangmetatool defines a target interface include directory setting, I'm not seeing any other properties being set, so if compilation switches need to be propagated from imported targets to clients, that's not happening.

**Comment by vaibhav-y** [comment]
@LegalizeAdulthood I'm trying to reproduce this, what was the command line you used for building and configuring clang?

**Comment by LegalizeAdulthood** [comment]
Nothing custom, just `cmake -G "Unix Makefiles" ../llvm` where my directory structure looks like:

clang/llvm - source
clang/build - build directory

**Comment by dbeer1** [comment]
I think the issue is that you are not setting `-DLLVM_REQUIRES_RTTI=1` when running cmake. Most distros set this and I guess rtti is turned off explicitly by llvm/clang if not set.

Can you use `cmake -DLLVM_REQUIRES_RTTI=1` to configure llvm/clang? I would suggest `-DLLVM_REQUIRES_EH=1` as well to turn on exception support.

**Comment by dbeer1** [comment]
See for example the debian source package (which ubuntu's llvm package is based on too): https://salsa.debian.org/pkg-llvm-team/llvm-toolchain/blob/8/debian/rules#L395

**Comment by dbeer1** [comment]
Sorry, edited above, the correct flag is `-DLLVM_ENABLE_RTTI=1`

**Comment by dbeer1** [comment]
We could possibly support this either way by using the LLVM cmake modules: https://github.com/llvm-mirror/llvm/blob/release_80/cmake/modules/AddLLVM.cmake#L30

**Comment by dbeer1** [comment]
I put in #39 which should handle this automatically, can you please try building using that branch @LegalizeAdulthood ?
