### ISSUE TITLE
clangmetatool fails if it can't find gtest

### ISSUE THREAD

**Issue by LegalizeAdulthood** [bloomberg/clangmetatool#38]
**Describe the bug**
Missing gtest causes clangmetatool to fail to build

**To Reproduce**
1. Clone clangmetatool
2. Configure a build with cmake without gtest on your system
3. clangmetatool fails to configure

**Expected behavior**
I should be able to build and install clangmetatool without building and running the gtest test suite

**Environment (please complete the following information):**
 - Happens on both Windows and Linux

**Additional context**
The workaround is to simply comment out the bottom of the `CMakeLists.txt` where it looks for gtest and adds the test subdirectory.

Suggested fix is to look for gtest as a non-required package and if found add the test directory.

**Comment by dbeer1** [comment]
How about something like `-DBUILD_TESTING=ON/OFF` to disable testing. Rather than just have tests turn themselves off, if you build with testing on then you need to have gtest installed, if testing is off then it won't try to build them

**Comment by dbeer1** [comment]
https://cmake.org/cmake/help/latest/module/CTest.html
